### ISSUE TITLE
Remove feeAssetHash arg from buildTx and make buildTx a method of WalletInterface

### ISSUE THREAD

**Issue by altafan** [vulpemventures/ldk#12]
If we refactored the existing toOutputScriptWithoutNetwork to a simpler networkFromAddress, we can drop the network argument of the buildTx method.

**Comment by tiero** [comment]
There i enymore network argument, https://github.com/vulpemventures/ldk/blob/master/src/transaction.ts#L10, but we have now feeAssetHash.

I think the best way would be another here, passing the network at constrUctor time in `new Wallet`

**Comment by louisinger** [comment]
This issue can be closed: fixed in #11 cc @tiero
