### ISSUE TITLE
Wallet restoration failure

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/ldk#136]
I notice this error when running Tdex App in prod/debug mode `NODE_ENV=production ionic capacitor run ios --external --prod --debug` during restoration of a big wallet.

<img width="1546" alt="Screenshot 2022-08-30 at 21 26 33" src="https://user-images.githubusercontent.com/4022128/187525834-a246234a-6ce6-4617-a24b-3d1ef9e298a2.png">

- The app is calling both `utxosFetchGenerator` and `fetchAndUpdateTxs`
- One of this call fails: https://electrs-batch-mempool.sevenlabs.io/addresses/utxo
- LDK throws here https://github.com/vulpemventures/ldk/blob/master/src/explorer/api.ts#L255

We should make sure `transactions` is an array or using `?` operator.

**Comment by louisinger** [comment]
it seems that the tdex-sdk is using[ ldk 0.5.6](https://github.com/tdex-network/tdex-sdk/blob/master/package.json#L58), 0.5.7 may fix it due to hex batching change. if not, I've added a "fallback to empty array" in PR #137

**Comment by Janaka-Steph** [comment]
No `^0.5.6` will install 0.5.7
