### ISSUE TITLE
Add Firefox-extension link and mention in ReadMe

### ISSUE THREAD

**Issue by Donach** [vulpemventures/ldk#146]
Hello!
Just discovered your extension, and was a bit saddened you don't have FF extension, but eventually found you do!
https://addons.mozilla.org/en-US/firefox/addon/marinawallet/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

If you can confirm it's made by you, it would be cool to add it on the readme!

Thanks!

**Comment by Janaka-Steph** [comment]
Hello @Donach! Yes Marina is available on Firefox, the link is correct. But you opened your issue on the wrong repo :)

**Comment by Donach** [comment]
Oh sorry, was on phone and overlooked this 😆
