### ISSUE TITLE
esploraTxToTxInterface should check if input is pegin before fetching tx 

### ISSUE THREAD

**Issue by Janaka-Steph** [vulpemventures/ldk#71]
The txid of a claim transaction input is the txid of the mainchain transaction. However `esploraTxToTxInterface` tries to fetch tx from the Liquid chain.

https://github.com/vulpemventures/ldk/blob/master/src/explorer/esplora.ts#L66

**Comment by louisinger** [comment]
closed by https://github.com/vulpemventures/ldk/pull/75 ?
