### ISSUE TITLE
[Proposal] Utxos could be computed from transactions

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/ldk#90]
Currently, we are using LDK to update the "wallet blockchain state". It means that we are fetching transactions and unspent from explorer (via `fetchAndUnblindUtxos` and `fetchAndUnblindTxs`).

There are two drawbacks using this methods:
- firstly, for each wallet address we need to send two requests to the explorer (one time for transactions and another one for unspents). This can be a problem if the explorer has a request limit.
- We also unblind the output two times: one time while we fetch it as utxo and another one while we fetch the transaction.

We can do something smarter because `fetchAndUnblindTxs` returns all the data needed to compute the utxos set (from transactions). We can easily implement a **reducer** function applied to `TxInterface` array in order to compute the **unblinded unspents**. It could let to save half of the requests sent to the explorer and unblind only one time the confidential outputs. It also reduces the complexity of "wallet updater" --> we only need to watch for a transaction and then compute the utxos. No need anymore to watch the unspents.

**Comment by tiero** [comment]
ACK
